namespace SolarflowServer.DTOs.Settings
{
    /// <summary>
    /// Represents the data transfer object used to update user settings.
    /// </summary>
    public class ChangeUserDTO
    {
        /// <summary>
        /// Gets or sets the full name of the user.
        /// </summary>
        public string Fullname { get; set; }

        /// <summary>
        /// Gets or sets the amount of energy consumed from the grid in kilowatt-hours (kWh).
        /// </summary>
        public double GridKWh { get; set; }

        /// <summary>
        /// Gets or sets the amount of energy generated by solar panels in kilowatt-hours (kWh).
        /// </summary>
        public double SolarKWh { get; set; }

        /// <summary>
        /// Gets or sets the latitude of the user's location.
        /// </summary>
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or sets the longitude of the user's location.
        /// </summary>
        public double Longitude { get; set; }
    }
}
