namespace SolarflowServer.DTOs.Authentication;

/// <summary>
/// Represents the data transfer object used to retrieve user information.
/// </summary>
public class GetUserDTO
{
    /// <summary>
    /// Gets or sets the full name of the user.
    /// </summary>
    public string Fullname { get; set; }

    /// <summary>
    /// Gets or sets the URL or path to the user's profile photo.
    /// </summary>
    public string Photo { get; set; }

    /// <summary>
    /// Gets or sets the email address of the user.
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the user account was created.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the user has permission to view the account.
    /// </summary>
    public bool HasViewAccount { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy consumed from the grid in kilowatt-hours (kWh).
    /// </summary>
    public double GridKWh { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy generated by solar panels in kilowatt-hours (kWh).
    /// </summary>
    public double SolarKWh { get; set; }

    /// <summary>
    /// Gets or sets the latitude of the user's location.
    /// </summary>
    public double Latitude { get; set; }

    /// <summary>
    /// Gets or sets the longitude of the user's location.
    /// </summary>
    public double Longitude { get; set; }
}