namespace SolarflowServer.DTOs.Hub;

/// <summary>
/// Represents the data transfer object for an energy record.
/// </summary>
public class EnergyRecordDTO
{
    /// <summary>
    /// Gets or sets the unique identifier of the energy record.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the associated application user.
    /// </summary>
    public int ApplicationUserId { get; set; }

    /// <summary>
    /// Gets or sets the timestamp of the energy record.
    /// </summary>
    public DateTime Timestamp { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy consumed by the house in kilowatt-hours (kWh).
    /// </summary>
    public double House { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy drawn from the grid in kilowatt-hours (kWh).
    /// </summary>
    public double Grid { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy generated by solar panels in kilowatt-hours (kWh).
    /// </summary>
    public double Solar { get; set; }

    /// <summary>
    /// Gets or sets the amount of energy stored in the battery in kilowatt-hours (kWh).
    /// </summary>
    public double Battery { get; set; }
}